# Site settings
title: Areen Khalaila
email: akhalaila@tulane.edu
address: New Orleans, La
description: > # this means to ignore newlines until "baseurl:"
  PhD student at Tulane University.
# baseurl: "/personal_website"  # the subpath of your site, e.g., /blog
# url: "https://areenkh.github.io/personal_website"  # the base hostname & protocol for your site
# production_url: "https://areenkh.github.io/personal_website"
baseurl: ""  # the subpath of your site, e.g., /blog
url: "https://www.areenkh.com"  # the base hostname & protocol for your site
production_url: "https://www.areenkh.com"
github_username: areenkh
permalink: /blog/:year/:month/:title.html

twitter: 
  username: khalaila_areen

sass:
  style: compressed

collections:
  posters:
    output: true
    permalink: /posters/:title/
  publications:
    output: false
  symposiums:
    output: true
    permalink: /symposiums/:title/

jekyll-mentions:
  base_url: https://twitter.com

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
